alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: aoifekanemusic.com
  type: PRIMARY
  zone: aoifekanemusic.com
- domain: www.aoifekanemusic.com
  type: ALIAS
  zone: aoifekanemusic.com
- domain: aofiekane.com
  type: ALIAS
  zone: aofiekane.com
- domain: www.aofiekane.com
  type: ALIAS
  zone: aofiekane.com
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: aofiekane
    match:
      path:
        prefix: /
name: aofiekane
region: nyc
services:
- build_command: npm install
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: dailyflowlabs/aofiekane
  http_port: 3000
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: aofiekane
  run_command: npm run start
  source_dir: /
